using System;
using System.Collections.Generic;
using BLRI.Manager.Interfaces.Core;
using BLRI.ViewModel.Animals;
using BLRI.ViewModel.LookUp;

namespace BLRI.Manager.Interfaces.Animals
{
    public interface IAnimalManager: IBaseService<AnimalViewModel>
    {
        IEnumerable<DropdownViewModel<Guid>> GetAnimalsDropdown(int categoryId);

        List<AnimalListViewModel> GetAnimalListBy();
        AnimalListViewModel GetAllInfoById(Guid id);
        IEnumerable<DropdownViewModel<Guid>> GetDamSireDropdownByCategory(int categoryId, int genderId);

        string GetAutogeneratedAnimalId(string prefix);
    }
}
